submit50:
  files: &submit50_files
    - !exclude "*"
    - !require Assignment_3.py
    - !require Assignment_1.py
    - !require Assignment_2.py
check50:
  checks:  foo.py
  files: *submit50_files

