submit50:
  files: &submit50_files
    - !exclude "*"
    - !require Assignment_6.py
check50:
  checks:  foo.py
  files: *submit50_files
  dependencies:
    - pandas
    - scikit-learn
    - statsmodels.formula.api
